In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
datos = sns.load_dataset('titanic')
datos

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [4]:
datos.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
datos.drop('class', axis=1, inplace=True)
datos.drop('who', axis=1, inplace=True)
datos.drop('adult_male', axis=1, inplace=True)
datos.drop('deck', axis=1, inplace=True)
datos.drop('embark_town', axis=1, inplace=True)
datos.drop('alive', axis=1, inplace=True)
datos.drop('alone', axis=1, inplace=True)
datos

     survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
codificador = LabelEncoder()
datos['sex'] = codificador.fit_transform(datos['sex'])
datos

     survived  pclass  sex   age  sibsp  parch     fare embarked
0           0       3    1  22.0      1      0   7.2500        S
1           1       1    0  38.0      1      0  71.2833        C
2           1       3    0  26.0      0      0   7.9250        S
3           1       1    0  35.0      1      0  53.1000        S
4           0       3    1  35.0      0      0   8.0500        S
..        ...     ...  ...   ...    ...    ...      ...      ...
886         0       2    1  27.0      0      0  13.0000        S
887         1       1    0  19.0      0      0  30.0000        S
888         0       3    0   NaN      1      2  23.4500        S
889         1       1    1  26.0      0      0  30.0000        C
890         0       3    1  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [7]:
copiaDatos = datos.copy()

In [8]:
# DIvidir el conjunto en X explicativas y Y respuestas
y = datos['survived']
datos.drop('survived', axis=1, inplace=True)
datos

     pclass  sex   age  sibsp  parch     fare embarked
0         3    1  22.0      1      0   7.2500        S
1         1    0  38.0      1      0  71.2833        C
2         3    0  26.0      0      0   7.9250        S
3         1    0  35.0      1      0  53.1000        S
4         3    1  35.0      0      0   8.0500        S
..      ...  ...   ...    ...    ...      ...      ...
886       2    1  27.0      0      0  13.0000        S
887       1    0  19.0      0      0  30.0000        S
888       3    0   NaN      1      2  23.4500        S
889       1    1  26.0      0      0  30.0000        C
890       3    1  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [9]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    int32
 2   age       714 non-null    float64
 3   sibsp     891 non-null    int64
 4   parch     891 non-null    int64
 5   fare      891 non-null    float64
 6   embarked  889 non-null    object
dtypes: float64(2), int32(1), int64(3), object(1)
memory usage: 45.4+ KB

In [10]:
print(datos.isnull().sum())

pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(datos, y, test_size=0.3)

In [13]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, Y_train)

ValueError: could not convert string to float: 'C'

In [14]:
datosActualizados = datos.dropna(axis=1)
datosActualizados

     pclass  sex  sibsp  parch     fare
0         3    1      1      0   7.2500
1         1    0      1      0  71.2833
2         3    0      0      0   7.9250
3         1    0      1      0  53.1000
4         3    1      0      0   8.0500
..      ...  ...    ...    ...      ...
886       2    1      0      0  13.0000
887       1    0      0      0  30.0000
888       3    0      1      2  23.4500
889       1    1      0      0  30.0000
890       3    1      0      0   7.7500

[891 rows x 5 columns]

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(datosActualizados, y, test_size=0.3)
lr.fit(X_train, Y_train)
pred = lr.predict(X_test)

In [16]:
pred

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0], dtype=int64)

In [17]:
from sklearn import metrics

In [18]:
print(metrics.accuracy_score(pred, Y_test))

0.7985074626865671

## Rellenar datos faltante -inputar

imputar con:
 - *Media*: Promedio de las datos
 - *Mediana*: Valor central
 - *Moda*: El mas repetido (unimodal, bimodal, multimodal o no hay moda)

In [19]:
datosRelleno = copiaDatos.copy()
datosRelleno['age'] = datosRelleno['age'].fillna(datosRelleno['age'].mean())
datosRelleno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    int32
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
dtypes: float64(2), int32(1), int64(4), object(1)
memory usage: 52.3+ KB

In [20]:
# Segmentar los grupo en entrenamiento y pruebas
y = datosRelleno['survived']
datosRelleno.drop('survived', axis=1, inplace=True)
X_train, X_test, Y_train, Y_test = train_test_split(datosRelleno, y, test_size=0.3, random_state=17)
lr.fit(X_train, Y_train)
pred = lr.predict(X_test)
print(metrics.accuracy_score(pred,Y_test))

ValueError: could not convert string to float: 'S'

### Otras formas de imputacion
- Interpoblacion lineal
- Rellenar con el dato de la siguiente fila
- Agregar una columna

In [21]:
imputados = copiaDatos.copy()
imputados['ageMissing'] = imputados['age'].isnull()
imputados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    int32
 3   age         714 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   embarked    889 non-null    object
 8   ageMissing  891 non-null    bool
dtypes: bool(1), float64(2), int32(1), int64(4), object(1)
memory usage: 53.2+ KB

In [22]:
# Segmentar el grupo en entrenamiento y pruebas
y = imputados['survived']
imputados.drop('survived', axis=1, inplace=True)

In [23]:
from sklearn.impute import SimpleImputer

In [24]:
imputador = SimpleImputer(strategy='median')
nuevosDatos = imputador.fit_transform(imputados)
imputados.info()

ValueError: Cannot use median strategy with non-numeric data:
could not convert string to float: 'S'

In [25]:
columnas = imputados.columns
imputados = pd.DataFrame(nuevosDatos, columns=columnas)
imputados

NameError: name 'nuevosDatos' is not defined

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
testDatos = copiaDatos[copiaDatos['age'].isnull() == True]
trainDatos = copiaDatos[copiaDatos['age'].isnull() == True]
y = trainDatos['age']
trainDatos.drop('age', axis=1, inplace=True)
lr = LinearRegression()
lr.fit(trainDatos, y)
testDatos.drop('age', axis=1, inplace=True)
estimada = lr.predict(testDatos)
testDatos['age'] =estimada
testDatos

C:\Users\karol\AppData\Local\Temp\ipykernel_7464\2059053464.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trainDatos.drop('age', axis=1, inplace=True)

ValueError: could not convert string to float: 'Q'